import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
//import MusicPlayer from "./components/musicPlayer";
import { Providers } from "./providers";
import Sidebar from "./components/sidebar";

const kanit = Kanit({
  subsets: ["latin", "thai"],
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>
        <Providers>
          <div className="relative w-screen h-screen flex flex-col">
            <Header className="border-b-1 sticky top-0 left-0" />
            <div className="flex flex-row shrink-0 overflow-hidden flex-1 h-full w-full">
              <Sidebar className="md:block hidden h-full w-64 shadow overflow-y-auto dark:border-r-white/20 dark:border-r-1" />
              <div className="w-full h-full flex-1 overflow-x-hidden">{children}</div>
            </div>
            {/*<MusicPlayer className="z-10 bg-white dark:bg-black w-full"/>*/}
          </div>
        </Providers>
      </body>
    </html>
  );
}
